@startuml
    entity users{
        *id :  BIGINT
        --
        *user_name : varchar(50)
        *password : varchar(255)
}

    entity ingredients{
        *id :  BIGINT
        --
        *name : varchar(50)
        *description : link,photo
        *category : varchar(200)
}

    entity cocktails {
        *id :  BIGINT
        --
        *name : varchar(50)
        *description : varchar(255)
        *recipe : varchar(2000)
        *ingredient_list : varchar(500)
        *evaluation : varchar(255)
        *view count : int
}

    entity tags {
        *id :  BIGINT
        --
        *name : varchar(50)
}

    entity rating{
        *user_id :  BIGINT
        *coctail_id :  BIGINT
        --
        * rating : int
}

    entity coctails_tags {
        *coctail_id : BIGINT
        *tags_id : BIGINT
    }

    users ||..o{ cocktails
    users ||..o{ rating
    cocktails }|..o| rating
    cocktails ||..|{ ingredients
    coctails_tags }|..o| cocktails
    coctails_tags }|..o| tags


@enduml