ALTER TABLE users
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE ingredient_categories
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE ingredients
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE cocktails
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE tags
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

