name: Deploy backend to AWS
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Deploy

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: Deploy to AWS
        run: |
          echo "${{ secrets.AWS_SSH_KEY  }}" | tr -d '\r' > key.pem
          chmod 400 key.pem
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
          scp -i key.pem target/cocktailbook-*.jar ubuntu@${{ secrets.AWS_HOST }}:/home/ubuntu/cocktailbook/cocktailbook.jar
          ssh -i key.pem ubuntu@${{ secrets.AWS_HOST }} fuser -k 8082/tcp | true
          ssh -i key.pem ubuntu@${{ secrets.AWS_HOST }} java -jar /home/ubuntu/cocktailbook/cocktailbook.jar --spring.config.location=classpath:/application.yml,/home/ubuntu/cocktailbook/application.yml -Xms512m -Xmx512m & disown